server:
  port: 8088

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password: root

  thymeleaf:
    #ª∫≥Âµƒ≈‰÷√
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
#    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.example.demo1.entity


mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



